blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # post views
    # path("", views.PostListView.as_view(), name="post_list"),
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "<int:post_id>/share/",
        views.post_share,
        name="post_share",
    ),
    path(
        "<int:post_id>/comment/",
        views.post_comment,
        name="post_comment",
    ),
    path("search/", views.post_search, name="post_search"),
    # if path converters like <int:id>/ is not sufficient,
    # we can use re_path() for complex URL patterns with Regex.
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')) # blog:post_list
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.db.models.functions import Now
from django.conf import settings
from django.urls import reverse

from taggit.managers import TaggableManager


# Default manager is the object manager
# Earlier -> Post.objects.all();
# Access -> Post.published.all()
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        # > Post.Status.choices
        #     [('DF', 'Draft'), ('PB', 'Published')]
        # > Post.Status.labels
        #     ['Draft', 'Published']
        # > Post.Status.values
        #     ['DF', 'PB']
        # > Post.Status.names
        #     ['DRAFT', 'PUBLISHED']
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    # related_name establishes reverse realtionship from User to Post.
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    tags = TaggableManager()

    # As timezone aware format, python generated default time.
    publish = models.DateTimeField(default=timezone.now)

    # DB current date and time, db generated default time.
    # publish = models.DateTimeField(db_default=Now())

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)

    # Managers
    objects = models.Manager()  # default
    published = PublishedManager()  # custom manager

    # While return data, sort the data
    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=["created"])]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


# Create form using Models
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    # Tag
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    # Pagination with 3 post per page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)  # default value is 1

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        # get last page, if page_number is out of range
        posts = paginator.page(paginator.num_pages)

    return render(request, "blog/post/list.html", {"posts": posts, "tag": tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    return render(
        request,
        "blog/post/detail.html",
        {"post": post, "comments": comments, "form": form},
    )

    # With try and catch
    # try:
    #     post = Post.published.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404("No Post Found")
    # return render(request, 'blog/post/detail.html', {'post': post})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} {cd['email']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']} comments:{cd['comments']}"

            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd["to"]],
            )
            sent = True
    else:
        form = EmailPostForm()

    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(
        request,
        "blog/post/comment.html",
        {"post": post, "form": form, "comment": comment},
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            # stemming and removing stop words in spanish
            # search_vector = SearchVector("title", "body", config='spanish')
            # search_vector = SearchVector("title", "body")
            # Giving weights
            # The default weights are D, C, B, and A, and they refer to the numbers 0.1, 0.2, 0.4, and 1.0, respectively.
            search_vector = SearchVector("title", weight="A") + SearchVector(
                "body", weight="B"
            )
            # search_query = SearchQuery(query, config='spanish')
            search_query = SearchQuery(query)
            results = (
                Post.published.annotate(
                    search=search_vector, rank=SearchRank(search_vector, search_query)
                )
                # .filter(search=search_query)
                .filter(rank__gte=0.3)
                .order_by("-rank")
            )

    return render(
        request,
        "blog/post/search.html",
        {"form": form, "query": query, "results": results},
    )

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <meta charset="UTF-8">
    <meta name="description" content="Blog Site">
    <meta name="keywords" content="HTML, Django">
    <meta name="author" content="Sandeep Dewangan">
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="content">
      {% block content %}
      {% endblock content %}
    </div>
    <div id="sidebar">
      <h2>My Blog</h2>
      I've written {% total_posts %} posts so far.
      <h3>Latest posts</h3>
      {% show_latest_posts 3 %}
      <h3>Most commented posts</h3>
      {% get_most_commented_posts as most_commented_posts %}
      <ul>
        {% for post in most_commented_posts %}
          <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}
    Add a comment
{% endblock title %}
{% block content %}
    {% if comment %}
        <h2>Your comment is added</h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Back to post</a>
        </p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
    Blog Details
{% endblock title %}
{% block content %}
    <h1>Blog Details</h1>
    <h2>{{ post.title }}</h2>
    <p>Published: {{ post.publish }} by {{ post.author }}</p>
    <p>{{ post.body|markdown }}</p>
    <p>
        <a href="{% url "blog:post_share" post.id %}">Share this post</a>
    </p>
    {% comment %} With allows to assign a value to a new variable {% endcomment %}
    {% comment %} With also avoids hitting db access mutiple times {% endcomment %}
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock content %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
    {% comment %} {{ form.as_p }} {% endcomment %}
    <div class="left">{{ form.name.as_field_group }}</div>
    <div class="left">{{ form.email.as_field_group }}</div>
    {{ form.body.as_field_group }}
    {% csrf_token %}
    <p>
        <input type="submit" value="Add a comment">
    </p>
</form>

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
    My Blog
{% endblock title %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}<h2>Post tagged with {{ tag.name }}</h2>{% endif %}
    {% for post in posts %}
        <h2>
            {% comment %} <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a> {% endcomment %}
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Publsihed {{ post.publish }} by {{ post.author }}
            {{ post.body|markdown|truncatewords_html:30 }}
        </p>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
    Search
{% endblock title %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}Found {{ total_results }} result{{ total_results|pluralize }}{% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p>
            <a href="{% url "blog:post_search" %}">Search again</a>
        </p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}
    Share a Post
{% endblock title %}
{% block content %}
    {% if sent %}
        <h1>E-mail sent successfully</h1>
        <p>{{ post.title }} was successfully sent to {{ form.cleaned_data.to }}</p>
    {% else %}
        <h1>Share {{ post.title }} by e-mail</h1>
        <form method="post" novalidate>
            {{ form.as_p }}
            {% csrf_token %}
            <input type='submit' value='Send email'>
        </form>
    {% endif %}
{% endblock content %}

blog/templates/pagination.html
<div>
    {% if page.has_previous %}<a href="?page={{ page.previous_page_number }}">Previous</a>{% endif %}
    Page {{ page.number }} of {{ page.paginator.num_pages }}
    {% if page.has_next %}<a href="?page={{ page.next_page_number }}">Next</a>{% endif %}
</div>